### ISSUE TITLE
Default Markdown engine in GitHub pages does not natively support definitions lists

### ISSUE THREAD

**Issue by muelerse** [SE-UP/RSE-UP#51]
The default md engine used for GitHub pages does not natively support definitions lists:
```
Heading.
:    Body
```

Is just rendered as 

> Heading.: Body

It should be rendered as 
<dl>
<dt>Heading.</dt>
<dd>Body</dd>
</dl>

Google suggests that adding the following to _config.yml should fix the definitions lists behavior:
```
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  hard_wrap: false
  enable_coderay: false
```

Unsure, if this breaks our current deploy pipeline. Suggest we only try this fix for the next iteration.
